apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: stackly-ecommerce
data:
  FLASK_ENV: "production"
  API_DEBUG: "false"
  LOG_LEVEL: "INFO"
  MYSQL_DB: "ecommerce"
  MYSQL_PORT: "3306"
