apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stackly-ecommerce
type: Opaque
stringData:
  username: ecommerce_user
  password: ecommerce_password
  root-password: root_password
