services:

  mysql:
    image: mysql:8
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_USER: ecommerce_user
      DB_PASSWORD: ecommerce_password
      DB_NAME: ecommerce

    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  mysql_data: