apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: stackly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

        - name: MYSQL_DATABASE
          value: ecommerce

        ports:
        - containerPort: 3306

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d

        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - "-h"
              - "127.0.0.1"
          initialDelaySeconds: 30
          periodSeconds: 10

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

      - name: init-sql
        configMap:
          name: mysql-init