apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: stackly-ecommerce
type: Opaque
stringData:
  root-password: root_password
  database-name: ecommerce
  database-user: ecommerce_user
  database-password: ecommerce_password
